# 当有改动推送到master分支时，启动Action
name: 自动部署

on:
  push:             # 有推送时就触发
    branches:
      - hexo

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: hexo

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g

    - name: 缓存 Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --save
        
    - name: 生成静态文件
      run: |
        hexo clean
        hexo generate
  
    - name: 部署Github
      env:
        TIME_ZONE: Asia/Shanghai
        # 要部署的公共仓库
        DEPLOY_REPO: hikyuuPX/hikyuuPX.github.io
        # 要部署的分支
        DEPLOY_BRANCH: master
        # 在私人源码仓库的设置中设置私钥：[SourceRepo]-->Settings-->Setrets-->Actions secrets
        GITHUB_PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
      run: |
        cd ./public && git init
        git config user.name "hwchu"
        git config user.email "hwchu2016@hotmail.com"
        git add .
        git commit -m "Automated Deployment By GitHub Actions @ $(date '+%Y-%m-%d %H:%M:%S') ${TIME_ZONE}"

        # --quiet: Suppress all output, including the listing of updated refs, unless an error occurs. Progress is not reported to the standard error stream.
        git push --force --quiet "https://$GITHUB_PERSONAL_TOKEN@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH


